---
  - name: Ensure docker is installed
    package:
      name: docker
      state: present
  - name: Add ec2-user to docker role
    user:
      name: ec2-user
      groups: "docker"
      append: True

  - name: Enable docker service
    service:
      name: docker
      state: started
      enabled: yes

  - name: Ensure docker python is installed
    pip:
      name: docker

      
  - name: Copy docker folder
    copy:
      src: "{{playbook_dir}}/docker/"
      dest: /home/ec2-user/docker/
      owner: ec2-user
      group: ec2-user
      remote_src: no
      mode: 0644
    
  - name: Build container
    docker_image:
      path: /home/ec2-user/docker
      name: docker-demo
      #tag: v1.1
      push: no
  
  - name: Run container
    docker_container:
      image: docker-demo #:v1.1
      name: demo
      env:
          S3BUCKET: "{{s3_bucket_name}}"
      ports:
        80:5000